import 'package:flutter/material.dart';

class HomeScreeen extends StatelessWidget {
  const HomeScreeen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('companentes de flutter'),
      ),
      body: ListView(
        children: const [
          Text('Kc campeon del  super bowl 58'),
          Text('Kc campeon del  super bowl 58'),
          Text('Kc campeon del  super bowl 58'),
          Text('Kc campeon del  super bowl 58'),
          Text('Kc campeon del  super bowl 58'),
          Text('Kc campeon del  super bowl 58'), 
          Text('Kc campeon del  super bowl 58'), 
          Text('Kc campeon del  super bowl 58'), 
          Text('Kc campeon del  super bowl 58'), 
          Text('Kc campeon del  super bowl 58'), 
          Text('Kc campeon del  super bowl 58'), 
          Text('Kc campeon del  super bowl 58'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('Kenia OS'),
          Text('KOS'),
        ],
      ),
    );
  }
}
